# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
    "i915" # Intel Integrated Graphics (Alder Lake)
    "intel_agp" # Needed by i915 sometimes
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "coretemp"
    "nct6775"
    "iwlwifi" # Intel Wi-Fi AX211 (from lshw description, driver is iwlwifi)
  ];
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/2aea9ef9-f83e-4de5-b886-b47fddcaa65a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-af78cda3-80af-443c-be71-afc63a787092".device = "/dev/disk/by-uuid/af78cda3-80af-443c-be71-afc63a787092";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/65BD-170B";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9fa3ca75-a27c-4909-9eca-f397dfa1d013"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault {
    system = "x86_64-linux";
  };
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
