ai_provider: ollama
ai_model: deepseek
nixos_folder: /home/przemek/Projects/nixos-config
log_level: info
ai_models:
    providers:
        gemini:
            name: Google Gemini
            description: Google's advanced AI models via API
            type: cloud
            base_url: https://generativelanguage.googleapis.com
            available: true
            supports_streaming: true
            supports_tools: true
            requires_api_key: true
            env_var: GEMINI_API_KEY
            models:
                gemini-1.5-flash:
                    name: Gemini 1.5 Flash
                    description: Fast and efficient Gemini model
                    type: chat
                    context_window: 1048576
                    max_tokens: 8192
                    recommended_for:
                        - fast
                        - general
                        - nixos
                    cost_tier: standard
                    default: true
        ollama:
            name: Ollama
            description: Local AI model provider for privacy-focused inference
            type: local
            base_url: http://localhost:11434
            available: true
            supports_streaming: true
            supports_tools: true
            requires_api_key: false
            models:
                deepseek-r1:32b:
                    name: DeepSeek-R1
                    description: DeepSeek-r1
                    # size: 32B
                    # type: chat
                    # context_window: 8192
                    # max_tokens: 4096
                    # recommended_for:
                    #     - nixos
                    #     - general
                    #     - coding
                    # requires_download: true
                    default: true
                llama3:
                    name: Llama 3
                    description: Meta's Llama 3 model for general-purpose tasks
                    size: 8B
                    type: chat
                    context_window: 8192
                    max_tokens: 4096
                    recommended_for:
                        - nixos
                        - general
                        - coding
                    requires_download: true
        openai:
            name: OpenAI
            description: OpenAI's GPT models via API
            type: cloud
            base_url: https://api.openai.com
            available: true
            supports_streaming: true
            supports_tools: true
            requires_api_key: true
            env_var: OPENAI_API_KEY
            models:
                gpt-3.5-turbo:
                    name: GPT-3.5 Turbo
                    description: Fast and cost-effective model
                    type: chat
                    context_window: 16385
                    max_tokens: 4096
                    recommended_for:
                        - general
                        - fast
                        - budget
                    cost_tier: standard
                    default: true
    selection_preferences:
        default_provider: ollama
        default_models:
            gemini: gemini-1.5-flash
            # ollama: llama3
            ollama: "deepseek-r1:32b"
            openai: "gpt-3.5-turbo"
        task_models:
            nixos_config:
                primary: ["ollama:deepseek-r1:32b", "gemini:gemini-1.5-flash"]
                fallback: ["openai:gpt-3.5-turbo"]
            # code_generation:
            #     primary: ["ollama:deepseek-r1:32b", "openai:gpt-4"]
            #     fallback: ["ollama:llama3"]
            debugging:
                primary: ["openai:gpt-4", "gemini:gemini-1.5-pro"]
                fallback: ["ollama:llama3"]
            general_help:
                primary: ["ollama:deepseek-r1:32b", "gemini:gemini-1.5-flash"]
                fallback: ["ollama:llama3"]
            complex_analysis:
                primary: ["openai:gpt-4", "gemini:gemini-1.5-pro"]
                fallback: ["ollama:llama3:70b"]
                # primary:
                #     - ollama:deepseek
                #     - gemini:gemini-1.5-flash
                # fallback:
                #     - ollama:llama3
                #     - openai:gpt-3.5-turbo
            # nixos_config:
            #     primary:
            #         - ollama:deepseek
            #         - gemini:gemini-1.5-flash
            #     fallback:
            #         - ollama:llama3
            #         - openai:gpt-3.5-turbo
    discovery:
        auto_discover: true
        cache_duration: 3600
        # check_timeout: 10
        max_retries: 2
mcp_server:
    host: localhost
    port: 8081
    socket_path: /tmp/nixai-mcp.sock
    auto_start: false
    documentation_sources:
        - https://wiki.nixos.org/wiki/NixOS_Wiki
        - https://nix.dev/manual/nix
        - https://nix.dev/
        - https://nixos.org/manual/nixpkgs/stable/
        - https://nix.dev/manual/nix/2.28/language/
        - https://nix-community.github.io/home-manager/
nixos:
    config_path: ~/Projects/nixos-config/flake.nix
    log_path: /var/log/nixos/nixos-rebuild.log
diagnostics:
    enabled: true
    threshold: 1
    error_patterns:
        - name: example_error
          pattern: (?i)example error regex
          error_type: custom
          severity: high
          description: Example error description
commands:
    # timeout: 30
    retries: 2
devenv:
    default_directory: .
    auto_init_git: true
    templates:
        golang:
            enabled: true
            default_version: "1.21"
            default_package_manager: ""
        nodejs:
            enabled: true
            default_version: "20"
            default_package_manager: npm
        python:
            enabled: true
            default_version: "311"
            default_package_manager: pip
        rust:
            enabled: true
            default_version: stable
            default_package_manager: ""
custom_ai:
    base_url: ""
    headers: {}
discourse:
    base_url: https://discourse.nixos.org
    api_key: ""
    username: ""
    enabled: true
